language: node_js
node_js:
  - "11"

cache: npm

script:
  - npm run build

deploy:
  provider: pages
  fqdn: docs.gitlocalize.com
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
